### ISSUE TITLE
"Error executing: fork/exec ./mavproxy.py: no such file or directory"

### ISSUE THREAD

**Issue by ElaineYao** [obicons/avis#24]
Hi,

I was running `bin/avis` under _avis_ folder in README.

```
elainey@elainey:~/avis$ ARDUPILOT_SRC_PATH=/home/elainey/ardupilot ARDUPILOT_GZ_PATH=/home/elainey/ardupilot_gazebo bin/avis -autopilot ardupilot

2021/09/19 20:01:40 Performing a dry run...
GPS readings: 0
Accel readings: 0
Gyro readings: 0
Compass readings: 0
Baro readings: 0
2021/09/19 20:01:47 Error executing: fork/exec ./mavproxy.py: no such file or directory
```
I downloaded the mavproxy and it can be used in Ardupilot normally. I was wondering why it will report `Error executing: fork/exec ./mavproxy.py: no such file or directory`. What is the current path when it says ` ./mavproxy.py ` ? And how can I solve this problem? Thank you,

Best,
Elaine

**Comment by obicons** [comment]
Hi Elaine,

Try adding `mavproxy.py` to the `Tools` directory in `ARDUPILOT_SRC_PATH`.

**Comment by ElaineYao** [comment]
Hi,

I've added `mavproxy.py` in the `Tools` directory and here is the structure in `Tools` directory. But it still reports the same error.

![image](https://user-images.githubusercontent.com/32926287/134089357-d950dfae-3d7c-4054-b164-d61ba7d63e31.png)
![image](https://user-images.githubusercontent.com/32926287/134089402-e1e32e1f-6f8f-4765-8bbf-14bc70797d73.png)

Thank you,

**Comment by obicons** [comment]
Can you try adding `mavproxy.py` to the `autotest`subdirectory in `Tools`? Also, make sure `mavproxy.py` has the executable permission set.

**Comment by ElaineYao** [comment]
Yeah. I add `mavproxy.py` under `Tools/autotest` and it works now. Thank you!

However, the output is like this and no more progress on that... I was wondering if there is anything else I need to do.

Output in terminal:
`2021/09/23 17:39:50 Performing a dry run...

`

Here is a screenshot of MAV console:
![image](https://user-images.githubusercontent.com/32926287/134601733-8194b18f-d30c-4587-aa39-68166425b350.png)

After a while, MAV console automatically closed and the output in the terminal is:
![image](https://user-images.githubusercontent.com/32926287/134602103-f5f4d774-eeb9-413c-8f4f-19e38817600e.png)

I'm quite confused as I guess something is wrong here.

**Comment by obicons** [comment]
Are you running the instrumented ArduPilot and Gazebo simulator?

**Comment by ElaineYao** [comment]
Hi,

I run the Ardupilot and Gazebo simulator first and then open a another terminal window to run Avis.
But it still says "Performing a dry run".

The operations I did are as follows:
1) In the terminal, cd `ardupilot_gazebo/`, run command `gazebo --verbose worlds/iris_arducopter_runway.world`

2) Open another window, cd `ardupilot/ArduCopter`, run command `sim_vehicle.py -f gazebo-iris --console --map` 
    Then run `STABILIZE> wp load ../Tools/autotest/ArduCopter_Tests/copter_terrain_mission.txt
`
    Run `STABILIZE> mode guided`
    Run `GUIDED> arm throttle`
    Run `GUIDED> takeoff 40`
    Run `GUIDED> mode auto`

3) Open another window, cd `avis/`, run command `ARDUPILOT_SRC_PATH=/home/elaine/ardupilot ARDUPILOT_GZ_PATH=/home/elaine/ardupilot_gazebo bin/avis -autopilot ardupilot`


I was wondering if there's something wrong with this process. Thanks in advance!

**Comment by obicons** [comment]
You shouldn't run ArduPilot or Gazebo separately. Avis will run them for you. You can try something like this:
```
./bin/avis -autopilot=ardupilot -workload.cmd='pipenv run python3 workloads/takeoff_and_hover.py {{.AutopilotName}}'  -output=bugs/  
```

**Comment by ElaineYao** [comment]
`.... workloads/takeoff_and_hover.py {{.AutopilotName}}`

Here, if I'm testing ardupilot, should I replace `{{.AutopilotName}}` with `ardupilot`?

If so, after I run this command(I also added the ARDUPILOT_SRC_PATH, etc,), it's still 'dry run..'

Then I run this part separately, `pipenv run python3 workloads/takeoff_and_hover.py ardupilot`, it reports errors too.

```
Traceback (most recent call last):
  File "workloads/takeoff_and_hover.py", line 27, in <module>
    t.test()
  File "workloads/takeoff_and_hover.py", line 7, in test
    time = self.time()
  File "/home/elaine/avis/workloads/target.py", line 44, in time
    return self.stub.Time(simulator_controller_pb2.TimeRequest())
  File "/home/elaine/.local/share/virtualenvs/avis-RASjfZWJ/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/elaine/.local/share/virtualenvs/avis-RASjfZWJ/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1633116438.422484247","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3158,"referenced_errors":[{"created":"@1633116438.422483062","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
>
```

**Comment by ElaineYao** [comment]
Hi @obicons,

I'm really interested in this implementation and was wondering if you could provide a virtual machine and related commands to run this project.

Much appreciated your time and patience.

**Comment by obicons** [comment]
Hi Elaine. Sure, I can package this work into a Docker image. I'm juggling a few things, but I'll try to push it sometime this week.

**Comment by ElaineYao** [comment]
@obicons Thanks in advance!

**Comment by YuJing63** [comment]
> pipenv run python3 workloads/takeoff_and_hover.py ardupilot


> @obicons Thanks in advance!

Have you run successfully now？
